"""empty message

Revision ID: 89346250af6a
Revises: 0d7038a197a0
Create Date: 2021-06-15 22:51:59.664347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89346250af6a'
down_revision = '0d7038a197a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('authorId', sa.Integer(), nullable=False),
    sa.Column('authorName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('authorId')
    )
    op.create_table('category',
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('categoryId'),
    sa.UniqueConstraint('categoryName')
    )
    op.create_table('book',
    sa.Column('isbnCode', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('totalCopies', sa.Integer(), nullable=False),
    sa.Column('availableCopies', sa.Integer(), nullable=False),
    sa.Column('publicationYear', sa.DATETIME(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('authorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['author.authorId'], ),
    sa.ForeignKeyConstraint(['categoryId'], ['category.categoryId'], ),
    sa.PrimaryKeyConstraint('isbnCode')
    )
    op.create_table('borrower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrowerId', sa.Integer(), nullable=True),
    sa.Column('bookId', sa.Integer(), nullable=True),
    sa.Column('dateofBorrow', sa.DateTime(), nullable=False),
    sa.Column('BorrowedTo', sa.DateTime(), nullable=False),
    sa.Column('actualReturnDate', sa.DateTime(), nullable=False),
    sa.Column('issuedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookId'], ['book.isbnCode'], ),
    sa.ForeignKeyConstraint(['borrowerId'], ['student.studentId'], ),
    sa.ForeignKeyConstraint(['issuedBy'], ['staff.staffId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrower')
    op.drop_table('book')
    op.drop_table('category')
    op.drop_table('author')
    # ### end Alembic commands ###
